# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12

platform:
  - x64

matrix:
  fast_finish: true

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install --global npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm --version
  - npm ci

test_script:
  - npm test

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 42qYgf76P/QjYb5QJ18gFFJ67iTlXc1QzEva9BFofwh5KzpF/QJ/pvRark1i3aux6uwL53zdDKTjXfy8Ozpqqk9DhnU5M1oA96bQYWOnmZU=

cache:
  # global npm cache
  - '%APPDATA%\\npm-cache'
